"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { CheckCircle2,LoaderCircle,ShieldCheck,Trophy,X } from "lucide-react";
import { clientApi,formatDate } from "@/lib/client-api";
import type { CoachBallot,CoachCredential,CoachVotingCandidate,CoachVotingCategory,CoachVotingContext } from "@/lib/awards-types";
import type { CatalogCategory,CatalogItem,Team } from "@/lib/types";

type Selection={teamId:string;candidateId:string;candidates:CoachVotingCandidate[];loading:boolean};
export default function CoachVotingV2Page(){
 const [credential,setCredential]=useState<CoachCredential|null>(null);const [context,setContext]=useState<CoachVotingContext|null>(null);const [contextId,setContextId]=useState("");const [selections,setSelections]=useState<Record<string,Selection>>({});const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [confirming,setConfirming]=useState(false);const [notice,setNotice]=useState("");const [error,setError]=useState("");
 async function loadContext(id:string){setSelections({});setContext(await clientApi<CoachVotingContext>(`/api/awards/coach-voting-v2/context?contextId=${encodeURIComponent(id)}`));}
 async function loadCredential(preferred?:string){const result=await clientApi<CoachCredential>("/api/awards/coach-access/me");setCredential(result);const list=result.contexts.filter(x=>x.active);const pick=list.find(x=>x.id===preferred)??list.find(x=>!x.submitted)??list[0];if(pick){setContextId(pick.id);await loadContext(pick.id);}else{setContextId("");setContext(null);}}
 useEffect(()=>{let cancelled=false;void (async()=>{try{const result=await clientApi<CoachCredential>("/api/awards/coach-access/me");if(cancelled)return;setCredential(result);const list=result.contexts.filter(x=>x.active);const pick=list.find(x=>!x.submitted)??list[0];if(pick){setContextId(pick.id);setSelections({});const loaded=await clientApi<CoachVotingContext>(`/api/awards/coach-voting-v2/context?contextId=${encodeURIComponent(pick.id)}`);if(!cancelled)setContext(loaded);}else{setContextId("");setContext(null);}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"Você não possui acesso à votação técnica.");}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[]);
 function update(categoryId:string,patch:Partial<Selection>){setSelections(cur=>{const p=cur[categoryId];return {...cur,[categoryId]:{teamId:patch.teamId??p?.teamId??"",candidateId:patch.candidateId??p?.candidateId??"",candidates:patch.candidates??p?.candidates??[],loading:patch.loading??p?.loading??false}}});}
 async function chooseTeam(category:CoachVotingCategory,teamId:string){update(category.id,{teamId,candidateId:"",candidates:[],loading:Boolean(teamId)});if(!teamId)return;try{const list=await clientApi<CoachVotingCandidate[]>(`/api/awards/coach-voting-v2/candidates?contextId=${encodeURIComponent(contextId)}&voteCategoryId=${encodeURIComponent(category.id)}&teamId=${encodeURIComponent(teamId)}`);update(category.id,{candidates:list,candidateId:category.targetType==="COACH"?(list[0]?.id??""):"",loading:false});}catch(e){update(category.id,{loading:false});setError(e instanceof Error?e.message:"Não foi possível carregar os candidatos.");}}
 const complete=useMemo(()=>context?.voteCategories.filter(c=>c.required).every(c=>selections[c.id]?.candidateId)??false,[context,selections]);
 const summary=useMemo(()=>!context?[]:context.voteCategories.map(category=>{const s=selections[category.id];const candidate=s?.candidates.find(x=>x.id===s.candidateId);return candidate?{category,candidate}:null;}).filter(Boolean) as Array<{category:CoachVotingCategory;candidate:CoachVotingCandidate}>,[context,selections]);
 async function submit(){if(!context||!complete)return;setSubmitting(true);setError("");try{await clientApi<CoachBallot>("/api/awards/coach-voting-v2/ballot",{method:"POST",body:JSON.stringify({contextId,votes:summary.map(({category,candidate})=>({voteCategoryId:category.id,candidateId:candidate.id}))})});setConfirming(false);setNotice("Voto deste contexto registrado com sucesso.");await loadCredential();}catch(e){setError(e instanceof Error?e.message:"Não foi possível registrar o voto.");}finally{setSubmitting(false);}}
 if(loading)return <div className="flex min-h-80 items-center justify-center"><LoaderCircle className="size-9 animate-spin text-cyan"/></div>;
 if(!credential)return <section className="rounded-3xl border border-coral/20 bg-panel p-6"><h1 className="display-title text-3xl">Votação indisponível</h1><p className="mt-3 text-sm text-muted">{error}</p></section>;
 if(!credential.contexts.length)return <FirstContextForm credential={credential} onCreated={async()=>loadCredential()} setError={setError}/>;
 const pending=credential.contexts.filter(x=>x.active&&!x.submitted);
 return <><header className="mb-7"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-amber"><Trophy className="size-5"/>Júri técnico</div><h1 className="display-title mt-3 text-3xl sm:text-4xl">Votação dos treinadores</h1><p className="mt-3 text-sm text-muted">Olá, <strong className="text-ivory">{credential.coachName}</strong>. Cada contexto liberado possui um voto independente.</p></header>
 <section className="mb-6 rounded-3xl border border-white/8 bg-panel p-5"><label className="grid gap-1.5 text-sm font-bold">Contexto<select className="field" value={contextId} onChange={e=>{const id=e.target.value;setContextId(id);setError("");setNotice("");void loadContext(id);}}>{credential.contexts.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.teamName} • divisão {x.divisionId} • categoria {x.categoryId}{x.submitted?" • VOTADO":""}</option>)}</select></label><p className="mt-2 text-xs text-muted">{pending.length?`${pending.length} contexto(s) ainda pendente(s).`:"Todos os contextos já foram votados."}</p></section>
 {notice?<p className="mb-5 rounded-xl border border-cyan/20 bg-cyan/7 px-4 py-3 text-sm font-bold text-cyan">{notice}</p>:null}
 {context?.submitted||context?.state==="SUBMITTED"?<section className="rounded-3xl border border-cyan/15 bg-panel p-6"><CheckCircle2 className="size-9 text-cyan"/><h2 className="mt-3 text-xl font-black">Voto registrado</h2><p className="mt-2 text-sm text-muted">Selecione acima outro contexto pendente, se houver.</p></section>:context?.state!=="OPEN"?<section className="rounded-3xl border border-white/8 bg-panel p-6"><Trophy className="size-9 text-amber"/><h2 className="mt-3 text-xl font-black">{context?.editionName}</h2><p className="mt-2 text-sm text-muted">{context?.state==="SCHEDULED"?`A votação abre em ${context.votingOpensAt?formatDate(context.votingOpensAt,{dateStyle:"short",timeStyle:"short"}):"breve"}.`:context?.state==="DRAFT"?"A organização ainda está preparando a votação.":"A votação desta edição já foi encerrada."}</p></section>:<><div className="grid gap-5">{context.voteCategories.map(category=>{const s=selections[category.id];return <section key={category.id} className="rounded-3xl border border-white/8 bg-panel p-5 sm:p-6"><h2 className="text-xl font-black">{category.label}</h2><div className={`mt-5 grid gap-4 ${category.targetType==="COACH"?"":"sm:grid-cols-2"}`}><label className="grid gap-1.5 text-sm font-bold">Time<select className="field" value={s?.teamId??""} onChange={e=>void chooseTeam(category,e.target.value)}><option value="">Selecione um time</option>{context.teams.filter(t=>category.targetType!=="COACH"||t.id!==context.representedTeamId).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{category.targetType!=="COACH"?<label className="grid gap-1.5 text-sm font-bold">Atleta<select className="field" value={s?.candidateId??""} onChange={e=>update(category.id,{candidateId:e.target.value})} disabled={!s?.teamId||s.loading}><option value="">{s?.loading?"Carregando...":"Selecione o atleta"}</option>{(s?.candidates??[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>:null}</div>{category.targetType==="COACH"?<p className="mt-3 flex gap-2 text-xs text-muted"><ShieldCheck className="size-4 shrink-0 text-cyan"/>Sua própria equipe não aparece no voto de Técnico.</p>:null}</section>})}</div>{error?<p className="mt-5 rounded-xl border border-coral/25 bg-coral/8 px-4 py-3 text-sm text-[#ffb195]">{error}</p>:null}<div className="mt-7 flex justify-end"><button type="button" className="btn-primary w-full sm:w-auto" disabled={!complete} onClick={()=>setConfirming(true)}>Registrar voto</button></div></>}
 {confirming?<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-4 backdrop-blur-sm sm:items-center"><div className="w-full max-w-xl rounded-3xl border border-white/10 bg-panel p-5"><div className="flex items-start justify-between"><h2 className="display-title text-2xl">Confira seus votos</h2><button type="button" onClick={()=>setConfirming(false)}><X className="size-5"/></button></div><div className="mt-5 grid gap-2">{summary.map(({category,candidate})=><div key={category.id} className="flex justify-between gap-4 rounded-xl bg-night/45 px-4 py-3"><span className="text-sm font-bold text-muted">{category.label}</span><span className="text-sm font-black">{category.targetType==="COACH"?candidate.teamName:candidate.name}</span></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" className="btn-ghost" onClick={()=>setConfirming(false)} disabled={submitting}>Revisar</button><button type="button" className="btn-primary" onClick={()=>void submit()} disabled={submitting}>{submitting?<LoaderCircle className="size-5 animate-spin"/>:null}{submitting?"Registrando...":"Confirmar votos"}</button></div></div></div>:null}</>;
}

function FirstContextForm({credential,onCreated,setError}:{credential:CoachCredential;onCreated:()=>Promise<void>;setError:(m:string)=>void}){
 const [divisions,setDivisions]=useState<CatalogItem[]>([]);const [categories,setCategories]=useState<CatalogCategory[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [divisionId,setDivisionId]=useState("");const [categoryId,setCategoryId]=useState("");const [teamId,setTeamId]=useState("");const [saving,setSaving]=useState(false);const category=categories.find(x=>String(x.id)===categoryId)??null;
 useEffect(()=>{clientApi<CatalogItem[]>(`/api/catalog/divisions?season=${credential.season}`).then(setDivisions).catch(()=>setDivisions([]));},[credential.season]);
 useEffect(()=>{if(!divisionId)return;clientApi<CatalogCategory[]>(`/api/catalog/categories?season=${credential.season}&divisionId=${encodeURIComponent(divisionId)}`).then(setCategories).catch(()=>setCategories([]));},[credential.season,divisionId]);
 useEffect(()=>{if(!category?.eventId)return;clientApi<Team[]>(`/api/catalog/teams?eventId=${encodeURIComponent(String(category.eventId))}`).then(setTeams).catch(()=>setTeams([]));},[category?.eventId]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!category||!teamId)return;setSaving(true);setError("");try{await clientApi("/api/awards/coach-access/contexts",{method:"POST",body:JSON.stringify({credentialId:credential.credentialId,eventId:category.eventId,divisionId:Number(divisionId),categoryId:Number(category.id),teamId})});await onCreated();}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar seu contexto.");}finally{setSaving(false);}}
 return <section className="rounded-3xl border border-cyan/15 bg-panel p-6 sm:p-8"><Trophy className="size-10 text-amber"/><h1 className="display-title mt-4 text-3xl">Informe onde você treina</h1><p className="mt-3 text-sm text-muted">Este será seu primeiro contexto. Contextos extras só poderão ser liberados pela administração.</p><form onSubmit={submit} className="mt-6 grid gap-4 md:grid-cols-3"><select className="field" value={divisionId} onChange={e=>{setDivisionId(e.target.value);setCategoryId("");setTeamId("");}} required><option value="">Divisão</option>{divisions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" value={categoryId} onChange={e=>{setCategoryId(e.target.value);setTeamId("");}} disabled={!divisionId} required><option value="">Categoria</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" value={teamId} onChange={e=>setTeamId(e.target.value)} disabled={!category?.eventId} required><option value="">Time</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button className="btn-primary md:col-span-3 md:justify-self-end" disabled={saving}>{saving?<LoaderCircle className="size-5 animate-spin"/>:null}{saving?"Salvando...":"Confirmar meu contexto"}</button></form></section>;
}
