"use client";
import { FormEvent,useEffect,useState } from "react";
import { Clipboard,LoaderCircle,Plus,ShieldCheck,UserX,XCircle } from "lucide-react";
import { clientApi,formatDate } from "@/lib/client-api";
import type { CoachAccessLinkInfo,CoachCredential,CreateCoachAccessLinkResult } from "@/lib/awards-types";
import type { AdminAwardEdition } from "@/lib/admin-awards-types";
import type { CatalogCategory,CatalogItem,Team } from "@/lib/types";

export default function TechnicalJuryAdminPage(){
 const [editions,setEditions]=useState<AdminAwardEdition[]>([]);const [editionId,setEditionId]=useState("");const [link,setLink]=useState<CoachAccessLinkInfo|null>(null);const [generatedUrl,setGeneratedUrl]=useState("");const [voters,setVoters]=useState<CoachCredential[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");
 async function load(id:string){const [l,v]=await Promise.all([clientApi<CoachAccessLinkInfo>(`/api/admin/awards/editions/${id}/coach-access-link`),clientApi<CoachCredential[]>(`/api/admin/awards/editions/${id}/coach-voters`)]);setLink(l);setVoters(v);}
 useEffect(()=>{clientApi<AdminAwardEdition[]>("/api/admin/awards/editions").then(async r=>{setEditions(r);if(r[0]){setEditionId(r[0].id);await load(r[0].id);}}).catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar o júri técnico.")).finally(()=>setLoading(false));},[]);
 async function generate(){setBusy("link");setError("");try{const r=await clientApi<CreateCoachAccessLinkResult>(`/api/admin/awards/editions/${editionId}/coach-access-link`,{method:"POST"});setGeneratedUrl(r.accessUrl);await load(editionId);}catch(e){setError(e instanceof Error?e.message:"Não foi possível gerar o link.");}finally{setBusy("");}}
 async function revoke(){if(!window.confirm("Revogar o link atual? Os treinadores já credenciados continuarão com acesso."))return;setBusy("link");try{await clientApi(`/api/admin/awards/editions/${editionId}/coach-access-link/revoke`,{method:"POST"});setGeneratedUrl("");await load(editionId);}catch(e){setError(e instanceof Error?e.message:"Não foi possível revogar o link.");}finally{setBusy("");}}
 if(loading)return <div className="flex min-h-80 items-center justify-center"><LoaderCircle className="size-9 animate-spin text-cyan"/></div>;
 return <div className="grid gap-6"><header><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-amber"><ShieldCheck className="size-5"/>Administração</div><h1 className="display-title mt-3 text-3xl sm:text-4xl">Júri técnico</h1><p className="mt-2 text-sm text-muted">Gere o link único e gerencie contextos extras dos treinadores.</p></header>
 <label className="grid max-w-sm gap-1.5 text-sm font-bold">Edição<select className="field" value={editionId} onChange={e=>{setEditionId(e.target.value);setGeneratedUrl("");void load(e.target.value);}}>{editions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 {error?<p className="rounded-xl border border-coral/25 bg-coral/8 px-4 py-3 text-sm text-[#ffb195]">{error}</p>:null}
 <section className="rounded-3xl border border-white/8 bg-panel p-5 sm:p-6"><h2 className="text-xl font-black">Link único de credenciamento</h2><p className="mt-2 text-sm text-muted">Status: <strong className={link?.available?"text-cyan":"text-muted"}>{link?.status??"NONE"}</strong></p>{generatedUrl?<div className="mt-4 flex gap-2"><input className="field min-w-0 flex-1" readOnly value={generatedUrl} onFocus={e=>e.currentTarget.select()}/><button type="button" className="btn-primary" onClick={()=>void navigator.clipboard.writeText(generatedUrl)}><Clipboard className="size-4"/>Copiar</button></div>:link?.available?<p className="mt-4 text-xs text-muted">Por segurança, o token completo só aparece no momento da geração. Para obter outro endereço, revogue e gere um novo.</p>:null}<div className="mt-5 flex gap-2">{!link?.available?<button type="button" className="btn-primary" onClick={()=>void generate()} disabled={busy==="link"}>{busy==="link"?<LoaderCircle className="size-4 animate-spin"/>:<Plus className="size-4"/>}Gerar link</button>:<button type="button" className="btn-ghost" onClick={()=>void revoke()} disabled={busy==="link"}><XCircle className="size-4"/>Revogar link</button>}</div></section>
 <section className="rounded-3xl border border-white/8 bg-panel p-5 sm:p-6"><h2 className="text-xl font-black">Treinadores credenciados</h2><p className="mt-1 text-sm text-muted">{voters.length} treinador(es) • {voters.reduce((s,x)=>s+x.contexts.length,0)} contexto(s)</p><div className="mt-5 grid gap-4">{voters.map(v=><CoachCard key={v.credentialId} voter={v} reload={async()=>load(editionId)} setError={setError}/>)}{!voters.length?<p className="py-8 text-center text-sm text-muted">Nenhum treinador credenciado.</p>:null}</div></section></div>;
}

function CoachCard({voter,reload,setError}:{voter:CoachCredential;reload:()=>Promise<void>;setError:(m:string)=>void}){
 const [adding,setAdding]=useState(false);const [busy,setBusy]=useState(false);
 async function deactivateContext(id:string){if(!window.confirm("Desativar este contexto?"))return;setBusy(true);try{await clientApi(`/api/admin/awards/coach-voters/${voter.credentialId}/contexts/${id}/deactivate`,{method:"POST"});await reload();}catch(e){setError(e instanceof Error?e.message:"Não foi possível desativar o contexto.");}finally{setBusy(false);}}
 async function deactivateCoach(){if(!window.confirm(`Desativar o acesso de ${voter.coachName}?`))return;setBusy(true);try{await clientApi(`/api/admin/awards/coach-voters/${voter.credentialId}/deactivate`,{method:"POST"});await reload();}catch(e){setError(e instanceof Error?e.message:"Não foi possível desativar o treinador.");}finally{setBusy(false);}}
 return <div className="rounded-2xl border border-white/7 bg-night/35 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><strong>{voter.coachName}</strong><small className="mt-1 block text-xs text-cyan">{voter.email}</small><small className="mt-1 block text-xs text-muted">Credenciado em {formatDate(voter.createdAt,{dateStyle:"short",timeStyle:"short"})}</small></div><button type="button" className="btn-ghost" onClick={()=>void deactivateCoach()} disabled={busy}><UserX className="size-4"/>Desativar</button></div><div className="mt-4 grid gap-2">{voter.contexts.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/6 bg-panel/60 px-4 py-3"><div><strong className="text-sm">{c.teamName}</strong><small className="mt-1 block text-xs text-muted">Divisão {c.divisionId} • Categoria {c.categoryId} • {c.source}</small></div><div className="flex items-center gap-2"><span className={`text-xs font-black ${c.submitted?"text-cyan":"text-amber"}`}>{c.submitted?"VOTOU":"PENDENTE"}</span>{!c.submitted?<button type="button" className="btn-ghost min-h-9! px-3! py-1.5! text-xs" onClick={()=>void deactivateContext(c.id)} disabled={busy}>Desativar</button>:null}</div></div>)}</div>{adding?<ContextForm voter={voter} done={async()=>{setAdding(false);await reload();}} cancel={()=>setAdding(false)} setError={setError}/>:<button type="button" className="btn-primary mt-4" onClick={()=>setAdding(true)}><Plus className="size-4"/>Adicionar categoria</button>}</div>;
}

function ContextForm({voter,done,cancel,setError}:{voter:CoachCredential;done:()=>Promise<void>;cancel:()=>void;setError:(m:string)=>void}){
 const [divisions,setDivisions]=useState<CatalogItem[]>([]);const [categories,setCategories]=useState<CatalogCategory[]>([]);const [teams,setTeams]=useState<Team[]>([]);const [divisionId,setDivisionId]=useState("");const [categoryId,setCategoryId]=useState("");const [teamId,setTeamId]=useState("");const [saving,setSaving]=useState(false);const category=categories.find(x=>String(x.id)===categoryId)??null;
 useEffect(()=>{clientApi<CatalogItem[]>(`/api/catalog/divisions?season=${voter.season}`).then(setDivisions).catch(()=>setDivisions([]));},[voter.season]);
 useEffect(()=>{if(!divisionId)return;clientApi<CatalogCategory[]>(`/api/catalog/categories?season=${voter.season}&divisionId=${encodeURIComponent(divisionId)}`).then(setCategories).catch(()=>setCategories([]));},[divisionId,voter.season]);
 useEffect(()=>{if(!category?.eventId)return;clientApi<Team[]>(`/api/catalog/teams?eventId=${encodeURIComponent(String(category.eventId))}`).then(setTeams).catch(()=>setTeams([]));},[category?.eventId]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!category||!teamId)return;setSaving(true);setError("");try{await clientApi(`/api/admin/awards/coach-voters/${voter.credentialId}/contexts`,{method:"POST",body:JSON.stringify({credentialId:voter.credentialId,eventId:category.eventId,divisionId:Number(divisionId),categoryId:Number(category.id),teamId})});await done();}catch(err){setError(err instanceof Error?err.message:"Não foi possível adicionar o contexto.");}finally{setSaving(false);}}
 return <form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl border border-cyan/15 bg-cyan/5 p-4 md:grid-cols-3"><select className="field" value={divisionId} onChange={e=>{setDivisionId(e.target.value);setCategoryId("");setTeamId("");}} required><option value="">Divisão</option>{divisions.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" value={categoryId} onChange={e=>{setCategoryId(e.target.value);setTeamId("");}} disabled={!divisionId} required><option value="">Categoria</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="field" value={teamId} onChange={e=>setTeamId(e.target.value)} disabled={!category?.eventId} required><option value="">Time</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><div className="flex gap-2 md:col-span-3 md:justify-end"><button type="button" className="btn-ghost" onClick={cancel}>Cancelar</button><button className="btn-primary" disabled={saving}>{saving?<LoaderCircle className="size-4 animate-spin"/>:null}Liberar votação</button></div></form>;
}
